export const ProductTestInfos = [
    {
        "picture": "https://www.marketingdirecto.com/wp-content/uploads/2018/09/uber.jpg",
        "productName": "Alpha Suite",
        "productShortDescription": "Suite de productividad alfa, completa y versátil",
        "longDescription": "Alpha Suite ofrece una gama completa de herramientas de productividad diseñadas para automatizar procesos, facilitar la colaboración en equipo y mejorar la gestión de tareas y proyectos. Es ideal para empresas que buscan optimizar sus operaciones y aumentar su eficiencia operativa.",
        "MediaLink": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        "ComentsCount": "45",
        "productPlatform": "Android",
        "softwareProductType": "SaaS",
        "productCategory": "Business",
        "RatingCount": 110
    },
    {
        "picture": "https://applicantes.com/wp-content/uploads/2023/03/crear-logotipo-empresa-financiera.jpeg",
        "productName": "Beta Tools",
        "productShortDescription": "Herramientas para análisis y gestión de datos",
        "longDescription": "Beta Tools facilita la comprensión profunda de grandes volúmenes de datos con herramientas avanzadas de visualización y análisis. Este producto es esencial para las organizaciones que desean extraer información valiosa y mejorar la toma de decisiones estratégicas.",
        "MediaLink": "https://www.youtube.com/watch?v=VbfpW0pbvaU",
        "ComentsCount": "67",
        "productPlatform": "Web",
        "softwareProductType": "PaaS",
        "productCategory": "Analytics",
        "RatingCount": 75
    },
    {
        "picture": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCWmfjBMhFkZQkt8TZWAzES80yyCGIfp20gxL6AJL0JA&s",
        "productName": "Gamma Graphics",
        "productShortDescription": "Software de diseño y modelado 3D",
        "longDescription": "Gamma Graphics es una solución de software líder para el diseño, modelado y animación 3D. Perfecto para arquitectos, ingenieros y diseñadores, ofrece herramientas sofisticadas para crear visualizaciones detalladas y realistas que impulsan la creatividad y la precisión.",
        "MediaLink": "https://www.youtube.com/watch?v=xvFZjo5PgG0",
        "ComentsCount": "89",
        "productPlatform": "Windows",
        "softwareProductType": "Desktop",
        "productCategory": "Design",
        "RatingCount": 55
    },
    {
        "picture": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/construction-company-logo%2C-real-estate-logo-%28-design-template-10b40dd4d995ad60d9b68696f4854c36_screen.jpg?ts=1669056348",
        "productName": "Delta Database",
        "productShortDescription": "Gestión de bases de datos en la nube",
        "longDescription": "Delta Database es un sistema innovador de gestión de bases de datos en la nube que proporciona alta disponibilidad, seguridad robusta y escalabilidad sin precedentes. Es ideal para empresas que necesitan manejar grandes cantidades de datos con facilidad y eficiencia.",
        "MediaLink": "https://www.youtube.com/watch?v=s7wmiS2mSXY",
        "ComentsCount": "120",
        "productPlatform": "iOS",
        "softwareProductType": "IaaS",
        "productCategory": "Database",
        "RatingCount": 98
    },
    {
        "picture": "https://t1.uc.ltmcdn.com/es/posts/5/9/1/_50195_9_600.jpg",
        "productName": "Epsilon Email",
        "productShortDescription": "Soluciones de correo electrónico empresarial",
        "longDescription": "Epsilon Email proporciona una solución de correo electrónico segura y escalable para empresas, con funciones avanzadas de protección contra spam y phishing. Perfecta para organizaciones que buscan mejorar la comunicación interna y externa con eficacia y seguridad.",
        "MediaLink": "https://www.youtube.com/watch?v=kfVsfOSbJY0",
        "ComentsCount": "43",
        "productPlatform": "Android",
        "softwareProductType": "SaaS",
        "productCategory": "Communication",
        "RatingCount": 85
    },
    {
        "picture": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSL2bVA7c9cWpl-blRBuiTdBSzVzZqRDv7ylQ2CdvkD5Q&s",
        "productName": "Zeta Sync",
        "productShortDescription": "Sincronización y backup en tiempo real",
        "longDescription": "Zeta Sync ofrece una solución robusta para la sincronización y backup en tiempo real, asegurando que los datos están seguros y accesibles desde cualquier lugar. Es una herramienta esencial para negocios que dependen de la disponibilidad continua de sus datos críticos.",
        "MediaLink": "https://www.youtube.com/watch?v=Z1BCujX3pw8",
        "ComentsCount": "39",
        "productPlatform": "Linux",
        "softwareProductType": "SaaS",
        "productCategory": "Storage",
        "RatingCount": 64
    },
    {
        "picture": "https://static-cse.canva.com/blob/951773/0750logotiposqueteinspiraran.jpg",
        "productName": "Eta Editor",
        "productShortDescription": "Editor de texto avanzado para desarrolladores",
        "longDescription": "Eta Editor es un editor de texto avanzado diseñado específicamente para desarrolladores. Con funcionalidades como resaltado de sintaxis, autocompletado de código y soporte para múltiples lenguajes, es una herramienta indispensable para la codificación eficiente y el desarrollo de software.",
        "MediaLink": "https://www.youtube.com/watch?v=oHg5SJYRHA0",
        "ComentsCount": "82",
        "productPlatform": "Web",
        "softwareProductType": "PaaS",
        "productCategory": "Development",
        "RatingCount": 49
    },
    {
        "picture": "https://w7.pngwing.com/pngs/831/520/png-transparent-brand-ambassador-logo-company-marketing-company-text-logo.png",
        "productName": "Theta Tracker",
        "productShortDescription": "Software de seguimiento de tiempo y proyectos",
        "longDescription": "Theta Tracker es una herramienta de gestión de proyectos que permite el seguimiento del tiempo, la asignación de tareas y la colaboración en equipo. Es ideal para equipos que buscan maximizar la productividad y garantizar la entrega a tiempo de proyectos.",
        "MediaLink": "https://www.youtube.com/watch?v=3H6hnFV-n6Q",
        "ComentsCount": "55",
        "productPlatform": "iOS",
        "softwareProductType": "SaaS",
        "productCategory": "Management",
        "RatingCount": 91
    },
    {
        "picture": "https://marketplace.canva.com/EAFAELFfY8o/1/0/1600w/canva-azul-y-violeta-informal-corporativo-desarrollo-de-aplicaci%C3%B3n-emprendimiento-empresa-logo-Olgzs4zIQXk.jpg",
        "productName": "Iota Insights",
        "productShortDescription": "Plataforma de análisis y visualización de datos",
        "longDescription": "Iota Insights es una plataforma integral para análisis y visualización de datos que permite a las empresas transformar datos complejos en insights accionables. Con potentes herramientas de análisis y visualización, los usuarios pueden descubrir patrones, tendencias y oportunidades para mejorar el rendimiento empresarial.",
        "MediaLink": "https://www.youtube.com/watch?v=oHg5SJYRHA0",
        "ComentsCount": "78",
        "productPlatform": "Mac",
        "softwareProductType": "Desktop",
        "productCategory": "Analytics",
        "RatingCount": 120
    },
    {
        "picture": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8apLGNyAau-WWDsnPRopt0Ng8I-AXIExyMWHHOJjXAQ&s",
        "productName": "Kappa Keeper",
        "productShortDescription": "Herramienta de seguridad y gestión de contraseñas",
        "longDescription": "Kappa Keeper es una herramienta de seguridad y gestión de contraseñas que garantiza la protección de datos sensibles y el acceso seguro a cuentas en línea. Con características como el almacenamiento encriptado y la generación de contraseñas seguras, ayuda a los usuarios a mantener su información privada protegida.",
        "MediaLink": "https://www.youtube.com/watch?v=oHg5SJYRHA0",
        "ComentsCount": "69",
        "productPlatform": "Windows",
        "softwareProductType": "SaaS",
        "productCategory": "Security",
        "RatingCount": 52
    },
    {
        "picture": "https://www.kienyke.com/sites/default/files/styles/interna_contenido_s/public/2023-04/JH%20de%20la%20Cruz%20historia_0001_9.jpg?itok=VZnny0nN",
        "productName": "Producto de prueba",
        "productShortDescription": "Producto de prueba creado...",
        "longDescription": "Este producto de prueba ha sido creado con el propósito de demostrar diversas funcionalidades y características de software. Aunque no representa un producto comercial, sirve como ejemplo para ilustrar cómo se pueden estructurar los datos de un producto en un contexto real.",
        "MediaLink": "https://www.youtube.com/watch?v=oHg5SJYRHA0",
        "ComentsCount": "53",
        "productPlatform": "IOS",
        "softwareProductType": "SaaS",
        "productCategory": "Productivity",
        "RatingCount": 90
    }
];
